"""Add index to Lead.phone

Revision ID: 020fae490fd1
Revises: 5f13720c8ef7
Create Date: 2026-03-10 17:50:51.077547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '020fae490fd1'
down_revision: Union[str, Sequence[str], None] = '5f13720c8ef7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_leads_phone'), 'leads', ['phone'], unique=False)
    op.create_index('ix_organizations_slug', 'organizations', ['slug'], unique=False)
    op.create_table_comment(
        'organizations',
        'Multi-tenant SaaS organizations. One org → many users.',
        existing_comment='Multi-tenant SaaS organizations',
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'organizations',
        'Multi-tenant SaaS organizations',
        existing_comment='Multi-tenant SaaS organizations. One org → many users.',
        schema=None
    )
    op.drop_index('ix_organizations_slug', table_name='organizations')
    op.drop_index(op.f('ix_leads_phone'), table_name='leads')
    # ### end Alembic commands ###
