"""call_logs external_call_id

Revision ID: 13e1cc7854d6
Revises: 88265117c17b
Create Date: 2026-02-26 17:22:36.519359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13e1cc7854d6'
down_revision: Union[str, Sequence[str], None] = '88265117c17b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('call_logs', sa.Column('external_call_id', sa.String(), nullable=False))
    op.create_index(op.f('ix_call_logs_external_call_id'), 'call_logs', ['external_call_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_call_logs_external_call_id'), table_name='call_logs')
    op.drop_column('call_logs', 'external_call_id')
    # ### end Alembic commands ###
