"""add_missing_user_columns

Revision ID: 179bd1effef4
Revises: e9ab826fc5e0
Create Date: 2026-02-23 17:34:02.828692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '179bd1effef4'
down_revision: Union[str, Sequence[str], None] = 'e9ab826fc5e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create ENUM type for role
    op.execute("CREATE TYPE userrole AS ENUM ('OWNER', 'ADMIN', 'AGENT')")
    
    # Add organizations.created_at
    op.add_column('organizations', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    
    # Add users columns as nullable first
    op.add_column('users', sa.Column('password_hash', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'AGENT', name='userrole'), nullable=True))
    op.add_column('users', sa.Column('first_name', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true()))
    op.add_column('users', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    
    # Migrate data: set password_hash from old password column
    op.execute('UPDATE users SET password_hash = password WHERE password IS NOT NULL')
    op.execute("UPDATE users SET password_hash = '' WHERE password_hash IS NULL")
    op.execute("UPDATE users SET role = 'AGENT' WHERE role IS NULL")
    
    # Now make them NOT NULL
    op.alter_column('users', 'password_hash', nullable=False)
    op.alter_column('users', 'role', nullable=False)
    
    # Drop old constraints and column
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_constraint(op.f('users_organization_id_fkey'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.drop_column('users', 'password')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(op.f('users_organization_id_fkey'), 'users', 'organizations', ['organization_id'], ['id'])
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.drop_column('users', 'role')
    op.drop_column('users', 'password_hash')
    op.drop_column('organizations', 'created_at')
    # Drop the ENUM type
    op.execute("DROP TYPE userrole")
    # ### end Alembic commands ###
