"""update_user_roles

Revision ID: 327fb4758cd7
Revises: 977799264388
Create Date: 2026-03-06 15:49:43.535605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '327fb4758cd7'
down_revision: Union[str, Sequence[str], None] = '977799264388'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.create_table_comment(
        'organizations',
        'Multi-tenant SaaS organizations',
        existing_comment='Multi-tenant SaaS organizations. One org → many users.',
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'organizations',
        'Multi-tenant SaaS organizations. One org → many users.',
        existing_comment='Multi-tenant SaaS organizations',
        schema=None
    )
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=False)
    # ### end Alembic commands ###
