"""add retry fields to lead

Revision ID: 69b679992d88
Revises: 82994cda8cc6
Create Date: 2026-02-25 15:16:27.886489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69b679992d88'
down_revision: Union[str, Sequence[str], None] = '82994cda8cc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('max_retries', sa.Integer(), nullable=True))
    op.alter_column('leads', 'retry_count',
               existing_type=sa.SMALLINT(),
               type_=sa.Integer(),
               nullable=True,
               existing_server_default=sa.text('0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('leads', 'retry_count',
               existing_type=sa.Integer(),
               type_=sa.SMALLINT(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_column('leads', 'max_retries')
    # ### end Alembic commands ###
