"""add retry_count to leads

Revision ID: 82994cda8cc6
Revises: f77182c70c37
Create Date: 2026-02-25 14:58:41.029337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82994cda8cc6'
down_revision: Union[str, Sequence[str], None] = 'f77182c70c37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('campaigns', 'call_delay_seconds',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.add_column('leads', sa.Column('retry_count', sa.SmallInteger(), nullable=False, server_default=sa.text('0')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'retry_count')
    op.alter_column('campaigns', 'call_delay_seconds',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    # ### end Alembic commands ###
