"""add bolna agent id to campaign

Revision ID: 85bf09c1b88d
Revises: 3584b02df9b1
Create Date: 2026-02-24 10:08:37.023996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85bf09c1b88d'
down_revision: Union[str, Sequence[str], None] = '3584b02df9b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('bolna_agent_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_campaigns_bolna_agent_id'), 'campaigns', ['bolna_agent_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_campaigns_bolna_agent_id'), table_name='campaigns')
    op.drop_column('campaigns', 'bolna_agent_id')
    # ### end Alembic commands ###
