"""add external_call_id to leads

Revision ID: 95f20c67cb95
Revises: f8b2f8c9a1b3
Create Date: 2026-02-27 12:47:46.047577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95f20c67cb95'
down_revision: Union[str, Sequence[str], None] = 'f8b2f8c9a1b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('external_call_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_leads_external_call_id'), 'leads', ['external_call_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leads_external_call_id'), table_name='leads')
    op.drop_column('leads', 'external_call_id')
    # ### end Alembic commands ###
