"""make slug unique

Revision ID: d5b57c327e65
Revises: 4b701a06f3bc
Create Date: 2026-03-05 18:40:08.489364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5b57c327e65'
down_revision: Union[str, Sequence[str], None] = '4b701a06f3bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('organizations', 'slug',
               existing_type=sa.VARCHAR(length=100),
               comment='Globally unique tenant identifier used in login and routing.',
               existing_comment='URL-friendly label used in login form. Not globally unique.',
               existing_nullable=False)
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=False)
    op.alter_column('organizations', 'slug',
               existing_type=sa.VARCHAR(length=100),
               comment='URL-friendly label used in login form. Not globally unique.',
               existing_comment='Globally unique tenant identifier used in login and routing.',
               existing_nullable=False)
    # ### end Alembic commands ###
