"""add is_processing to campaigns

Revision ID: f77182c70c37
Revises: fed15252e983
Create Date: 2026-02-25 14:41:19.611613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f77182c70c37'
down_revision: Union[str, Sequence[str], None] = 'fed15252e983'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('is_processing', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('campaigns', sa.Column('call_delay_seconds', sa.Integer(), nullable=False, server_default=sa.text('0')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaigns', 'call_delay_seconds')
    op.drop_column('campaigns', 'is_processing')
    # ### end Alembic commands ###
